#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by GUI_Scraper (Chrome Extension)

# 初めての場合は下記の2行を実行してください
# pip install playwright
# python -m playwright install chromium

import asyncio, csv, re, json, sys
from datetime import datetime, timezone, timedelta
from pathlib import Path
from playwright.async_api import async_playwright

SCHEMA_JSON = r'''{
  "fields": [
    {
      "attr": "text",
      "name": "名称",
      "proc": "text",
      "xpath": "//*[@id='main']/section[1]/article[1]/div[7]/table[1]/tbody[1]/tr[1]/td[1]/span[1]"
    },
    {
      "attr": "text",
      "name": "住所",
      "proc": "text",
      "xpath": "//table[contains(concat(' ', normalize-space(@class), ' '), ' jobTable ')]//tr[.//th[normalize-space(.)='住所']]/td[1]"
    }
  ]
}'''
SCHEMA = json.loads(SCHEMA_JSON)

SINGLE_ROW = True
CSV_SKIP_HEADER = True

JST = timezone(timedelta(hours=9))
def now_jst():
    return datetime.now(JST).strftime("%Y-%m-%d %H:%M:%S")

def apply_proc(val, proc):
    val = (val or "")
    if proc == "digits":
        return re.sub(r"\D+", "", val)
    elif proc == "yenToMan":
        t = re.sub(r"[ ,，\s]", "", val)
        yen = 0
        m1 = re.search(r"([\d.]+)万円", t)
        if m1: yen += round(float(m1.group(1)) * 10000)
        m2 = re.search(r"([\d.]+)億", t)
        if m2: yen += round(float(m2.group(1)) * 100000000)
        m3 = re.search(r"([\d.]+)万(?!円)", t)
        if m3: yen += round(float(m3.group(1)) * 10000)
        m4 = re.search(r"([\d.]+)円", t)
        if m4: yen += round(float(m4.group(1)))
        if not (m1 or m2 or m3 or m4):
            digs = re.findall(r"\d+", t)
            if digs: yen += int("".join(digs))
        return str(round(yen/10000)) if yen else ""
    elif proc == "dateYmd":
        x = val.strip()
        jp = re.search(r"(\d{4})\s*年\s*(\d{1,2})\s*月\s*(\d{1,2})\s*日", x)
        if jp:
            y, m, d = int(jp.group(1)), int(jp.group(2)), int(jp.group(3))
            return f"{y}/{m:02d}/{d:02d}"
        m1 = re.search(r"(\d{4})[\/-\.](\d{1,2})[\/-\.](\d{1,2})", x)
        if m1:
            y, m, d = int(m1.group(1)), int(m1.group(2)), int(m1.group(3))
            return f"{y}/{m:02d}/{d:02d}"
        return ""
    elif proc == "normalizeSpace":
        return re.sub(r"[\s\u3000]+", " ", val).strip()
    elif proc == "noSpaces":
        return re.sub(r"[\s\u3000]+", "", val)
    elif proc == "noNewlines":
        return re.sub(r"(\r?\n|\r)", "", val)
    else:
        return val.strip()

async def extract_page(page, schema, single_row):
    data = {}
    max_len = 0
    for fdef in schema.get("fields", []):
        xp   = (fdef.get("xpath") or "").strip()
        attr = (fdef.get("attr")  or "text").strip()
        proc = (fdef.get("proc")  or "text").strip()
        vals = []
        if xp:
            elems = await page.query_selector_all(f"xpath={xp}")
            limit = min(1, len(elems)) if single_row else len(elems)
            for i in range(limit):
                el = elems[i]
                if not el:
                    continue
                if attr == "text":
                    raw = await el.text_content() or ""
                elif attr == "html":
                    raw = await el.inner_html() or ""
                elif attr == "href":
                    raw = await el.evaluate("""(el)=>{const a=el.closest('a'); return a?a.href:(el.getAttribute('href')||'');}""") or ""
                elif attr == "src":
                    raw = await el.get_attribute("src") or ""
                else:
                    raw = await el.text_content() or ""
                vals.append(apply_proc(raw, proc))
        data[fdef["name"]] = vals
        if not single_row and len(vals) > max_len:
            max_len = len(vals)

    items = []
    if single_row:
        row = { name: (vals[0] if vals else "") for name, vals in data.items() }
        if "取得日時" not in row:
            row["取得日時"] = now_jst()
        items.append(row)
    else:
        rows = max(max_len, 1)
        for r in range(rows):
            row = {}
            for name, vals in data.items():
                row[name] = vals[r] if r < len(vals) else ""
            if "取得日時" not in row:
                row["取得日時"] = now_jst()
            items.append(row)
    return items

def empty_row_for_url(u):
    row = {"取得日時": now_jst(), "URL": u}
    for fdef in SCHEMA.get("fields", []):
        row[fdef["name"]] = ""
    return row

def ordered_cols_from_schema():
    base = ["取得日時", "URL"] + [f["name"] for f in SCHEMA.get("fields", [])]
    out = []
    for c in base:
        if c not in out:
            out.append(c)
    return out

async def main():
    input_csv  = sys.argv[1] if len(sys.argv) >= 2 else "input.csv"
    output_csv = sys.argv[2] if len(sys.argv) >= 3 else "output.csv"

    urls = []
    with open(input_csv, newline="", encoding="utf-8-sig") as rf:
        reader = csv.reader(rf)
        if CSV_SKIP_HEADER:
            next(reader, None)
        for row in reader:
            if not row:
                continue
            u = (row[0] or "").strip()
            if u.lower().startswith("http"):
                urls.append(u)

    ordered_cols = ordered_cols_from_schema()
    p = Path(output_csv)
    need_header = not (p.exists() and p.stat().st_size > 0)

    mode = "w" if need_header else "a"
    enc  = "utf-8-sig" if need_header else "utf-8"
    f = open(output_csv, mode, newline="", encoding=enc)
    writer = csv.DictWriter(
        f,
        fieldnames=ordered_cols,
        quoting=csv.QUOTE_ALL,
        lineterminator="\r\n"
    )
    if need_header:
        writer.writeheader(); f.flush()

    async with async_playwright() as pwt:
        browser = await pwt.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()
        for i, u in enumerate(urls, start=1):
            print(f"[{i}/{len(urls)}] GET {u}")
            try:
                await page.goto(u, wait_until="domcontentloaded", timeout=60000)
                await page.wait_for_timeout(400)

                # ★ 欠陥②の修正：実際に到達したURLを使う
                actual_url = page.url
                try:
                    first_xp = next((fd["xpath"] for fd in SCHEMA.get("fields", []) if fd.get("xpath")), None)
                    if first_xp:
                        await page.wait_for_selector(f"xpath={first_xp}", timeout=3000)
                except Exception:
                    pass

                items = await extract_page(page, SCHEMA, SINGLE_ROW)
                rows = []
                if not items:
                    rows.append(empty_row_for_url(actual_url))
                else:
                    for it in items:
                        row = empty_row_for_url(actual_url)
                        for fdef in SCHEMA.get("fields", []):
                            row[fdef["name"]] = it.get(fdef["name"], "")
                        if not row.get("取得日時"):
                            row["取得日時"] = now_jst()
                        rows.append(row)

                for row in rows:
                    for c in ordered_cols:
                        row.setdefault(c, "")
                        if isinstance(row[c], str):
                            row[c] = row[c].replace("\r\n", "\n").replace("\r", "\n")
                    writer.writerow(row)
                f.flush()  # 1URLごとに追記

            except Exception as e:
                print("  ! error:", e)
                row = empty_row_for_url(u)
                for c in ordered_cols:
                    row.setdefault(c, "")
                writer.writerow(row); f.flush()

        await browser.close()

    f.close()
    print(f"Appended {len(urls)} pages to {output_csv}")

if __name__ == "__main__":
    asyncio.run(main())
